name: Build PlaceholderAPI-DEV
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Configure build environment
      run: |
        chmod +x gradlew
        sed -i '/license {/a\    ignoreFailures = true' build.gradle.kts
        sed -i '/license {/a\    skipExistingHeaders = true' build.gradle.kts
        sed -i 's/failOnViolation = true/failOnViolation = false/' build.gradle.kts
    - name: Run development build
      run: |
        ./gradlew build \
          -DBUILD_NUMBER=$BUILD_NUMBER \
          -x licenseMain \
          -x licenseTest \
          -x javadoc \
          -x javadocJar
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PlaceholderAPI-DEV-${{ env.BUILD_NUMBER }}
        path: build/libs/*.jar
        retention-days: 3
